version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/manager-github-api
    ports:
      - "3001:3001"
    depends_on:
      - db
    stdin_open: true
    tty: true
